version: '3'
services:
  prometheus:
    image: gabecasis/prometheus:2
    ports:
      - "9090:9090"
    networks:
      - app-network
    restart: always
    volumes:
      - ./prometheus:/prometheus  # Persistent storage for Prometheus data
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml  # Custom Prometheus config

  grafana:
    image: gabecasis/grafana:2
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: always
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources  # Correct datasource path
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards  # Mount dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  app-network:
    driver: bridge