global:
  scrape_interval: 15s  # Scrape metrics every 15 seconds

scrape_configs:
  - job_name: 'flask_stock_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['3.94.148.26:8000']
