version: '3'
services:
  stock-app:
    build: ./stock-app
    ports:
      - "5001:5001"  # Flask app port
      - "8000:8000"  # Prometheus metrics port
    networks:
      - app-network
    volumes:
      # Use relative path for Linux environments
      # - ./stock-app/logs:/app/logs

      # Use absolute path for macOS to avoid Docker mount issues
      - /Users/guyabecassis/Desktop/Guy/Projects/Mid_Project/Mid_Project/stock-app/logs:/app/logs
    restart: always  # Ensure container restarts on failure

  prometheus:
    build: ./prometheus
    ports:
      - "9090:9090"  # Prometheus port
    networks:
      - app-network
    restart: always

  grafana:
    build: ./grafana
    ports:
      - "3000:3000"  # Grafana port
    networks:
      - app-network
    restart: always
    volumes:
      - ./grafana:/var/lib/grafana  # Persistent storage for Grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Default Grafana admin password
    depends_on:
      - loki  # Ensure Grafana starts after Loki

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"  # Loki port
    networks:
      - app-network
    restart: always
    volumes:
      - ./loki/config:/etc/loki/config
      - ./loki/data:/loki  # Loki data directory

  promtail:
    image: grafana/promtail
    container_name: promtail
    ports:
      - "9080:9080"
    volumes:
      - ./promtail/config/config.yml:/etc/promtail/config.yml
      - ./stock-app/logs:/var/log/stock-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
